### ISSUE TITLE
Validator - Level 2 requirements

### ISSUE THREAD

**Issue by yemijaiyeola** [WeAreSnook/human-services#9] opened 2021-03-02 14:33 UTC
**User Story**
As a data custodian, I need to validate that my data is compliant to the Level 2 standard (keyword search and taxonomies), so that I can be assured that I will gain all the benefits of full standard compliance.

**Why**
Level 2 is a definition

**What**
- Check that the data is using the ESD service taxonomy
- 

Level 2 - Supporting other parameters included in the standard - more advanced features such as taxonomies
e.g postcode, search for a postcode do we find a service registered at that postcode

**Comment by PorismDominicSkinner** [comment] 2021-03-11 16:07
This case seems to be more out validating against official standards rather than testing that the taxonomies loaded are actually searchable.

**Comment by ailsaleen** [comment] 2021-03-11 16:53
Duplicate of #5 so closing as finished

**Closed by ailsaleen** 2021-03-11 16:53 UTC
Labels: MVP, complexity: 8
